Repository 2021HYUopensource/super-mario-python, pull requests merged in 2021-12, with the labels that each got.

#12 [환경 만들기] 스테이지 관련 수정사항
  classes/Camera.py
  classes/Collider.py
  classes/Level.py
  classes/Menu.py
  classes/Pause.py
  classes/Sound.py
  classes/Tile.py
  classes/Win.py
  entities/EntityBase.py
  entities/Mario.py
  entities/Star.py
  img/items_white.png
  levels/1-1.json
  levels/1-2-test.json
  levels/Level1-1.json
  main.py
  sfx/smb_stage_clear.wav
  sprites/ItemAnimations.json
  traits/leftrightwalk.py
Labels: enviroments

#15 패키지 수정
  RL_Agent/Agent.md
  RL_Agent/Agents/__init__.py
  RL_Agent/Agents/creator.py
  RL_Agent/DQN/DQN_main_sys.py
  RL_Agent/DQN/__init__.py
  RL_Agent/DQN/agent.py
  RL_Agent/PPO/PPO_main_sys.py
  RL_Agent/PPO/agent.py
  RL_Agent/main.py
  RL_Agent/runs/Nov28_22-17-12_DESKTOP-LS47HSG/events.out.tfevents.1638105432.DESKTOP-LS47HSG
  RL_Agent/runs/Nov28_22-18-20_DESKTOP-LS47HSG/events.out.tfevents.1638105500.DESKTOP-LS47HSG
  RL_Agent/runs/Nov28_22-19-02_DESKTOP-LS47HSG/events.out.tfevents.1638105542.DESKTOP-LS47HSG
  RL_Agent/runs/Nov28_22-20-28_DESKTOP-LS47HSG/events.out.tfevents.1638105628.DESKTOP-LS47HSG
  RL_Agent/runs/Nov29_08-48-57_DESKTOP-LS47HSG/events.out.tfevents.1638143337.DESKTOP-LS47HSG
  RL_Agent/utils/Env_wrapper.py
  RL_Agent/utils/__init__.py
  RL_Agent/utils/img_preprocessing.py
Labels: documentation

#17 [FEAT] reawrd 수정- 가장 많이 간 기준으로 변경, 맵을 좀 더 쉽게 구성, 달리기 선택지 추가
  .gitignore
  classes/Input.py
  classes/LearningEnv.py
  levels/1-2-test.json
Labels: Reinforcement Learning, enviroments
